/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RockPaperScissors } from "./RockPaperScissors";

export { RockPaperScissors__factory } from "./factories/RockPaperScissors__factory";
